
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pabon
 */
public class ExShowtime extends javax.swing.JFrame {

    /**
     * Creates new form ExShowtime
     */
    public ExShowtime() {
        initComponents();
    }

    
    public ExShowtime(String info[][],int itr) {
        initComponents();
    
    DefaultTableModel model = (DefaultTableModel)ExShowtime_Table.getModel();
            String data[] = new String[7];

            for (int i = 0; i < itr; i++) {

                for (int j = 0; j < 7; j++) {
                    data[j] = info[i][j];
                }

                model.addRow(data);
            }
            
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ExShowtime_Table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ExShowtime_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "MovieName", "HallName", "StartingTime", "EndingTime", "TicketPrice"
            }
        ));
        ExShowtime_Table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(ExShowtime_Table);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Staff");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Ex Staff");

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("Tradings");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("Hall");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Join With");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
        String query = "SELECT * from ExShowtime INNER JOIN Hall ON ExShowtime.HallName = Hall.HallName";
      
            int itr = 0;
            
            String [][]info = new String [1000][12]; 
            
          try {
            Connection con;
         PreparedStatement ps;
         ResultSet rs;
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        
           con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=Register_Login;user=root;password=root");
           ps = con.prepareStatement(query);
           
    
                   
            rs = ps.executeQuery();  
            
           
          
          
         while(rs.next()){
               
         String []data = new String [10];
               
              
        info[itr][0]= rs.getString("Code");
        info[itr][1]= rs.getString("MovieName");
        info[itr][2]= rs.getString("HallName");      
        info[itr][3]= rs.getString("StartingTime");
        info[itr][4]= rs.getString("EndingTime");
        info[itr][5]= rs.getString("TicketPrice");
        
        
        info[itr][6]= rs.getString("HallType");
        info[itr][7]= rs.getString("TotalSeat");
      
                 
        itr++;
        
      
//JOptionPane.showMessageDialog(null,"Yes");
           
           }
           
      
        
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
        
  
        
       
   
        new ExShowtime_Join_Hall(info,itr).setVisible(true);
        setVisible(false);
          System.out.println(itr);        

// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String query = "SELECT * from ExShowtime INNER JOIN Staff ON ExShowtime.HallName = Staff.HallName";
      
            int itr = 0;
            
            String [][]info = new String [1000][12]; 
            
          try {
            Connection con;
         PreparedStatement ps;
         ResultSet rs;
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        
           con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=Register_Login;user=root;password=root");
           ps = con.prepareStatement(query);
           
    
                   
            rs = ps.executeQuery();  
            
           
          
          
         while(rs.next()){
               
         String []data = new String [10];
               
              
        info[itr][0]= rs.getString("Code");
        info[itr][1]= rs.getString("MovieName");
        info[itr][2]= rs.getString("HallName");      
        info[itr][3]= rs.getString("StartingTime");
        info[itr][4]= rs.getString("EndingTime");
        info[itr][5]= rs.getString("TicketPrice");
        
        
        info[itr][6]= rs.getString("StaffID");
        info[itr][7]= rs.getString("FirstName");
        info[itr][8]= rs.getString("LastName");
        info[itr][9]= rs.getString("StartingTime");
        info[itr][10]= rs.getString("EndingTime");
        info[itr][11]= rs.getString("Salary");
      
                 
        itr++;
        
      
//JOptionPane.showMessageDialog(null,"Yes");
           
           }
           
      
        
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
        
  
        
       
   
        new ExShowtime_Join_Staff(info,itr).setVisible(true);
        setVisible(false);
          System.out.println(itr);     
           
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
            String query = "SELECT * from ExShowtime INNER JOIN Tradings ON ExShowtime.Code = Tradings.Code";
      
            int itr = 0;
            
            String [][]info = new String [1000][10]; 
            
          try {
            Connection con;
         PreparedStatement ps;
         ResultSet rs;
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        
           con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=Register_Login;user=root;password=root");
           ps = con.prepareStatement(query);
           
    
                   
            rs = ps.executeQuery();  
            
           
          
          
         while(rs.next()){
               
         String []data = new String [10];
               
              
        info[itr][0]= rs.getString("Code");
        info[itr][1]= rs.getString("MovieName");
        info[itr][2]= rs.getString("HallName");      
        info[itr][3]= rs.getString("StartingTime");
        info[itr][4]= rs.getString("EndingTime");
        info[itr][5]= rs.getString("TicketPrice");
        
        
        info[itr][6]= rs.getString("ID");
        info[itr][7]= rs.getString("Cost");
        info[itr][8]= rs.getString("CustomerName");
        info[itr][9]= rs.getString("Phone");
        
      
                 
        itr++;
        
      
//JOptionPane.showMessageDialog(null,"Yes");
           
           }
           
      
        
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
        
  
        
       
   
        new ExShowtime_Join_Staff(info,itr).setVisible(true);
        setVisible(false);
          System.out.println(itr); 
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExShowtime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExShowtime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExShowtime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExShowtime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExShowtime().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ExShowtime_Table;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
