
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Rifat Waheed
 */
public class Hall_Join extends javax.swing.JFrame {

    /**
     * Creates new form Hall_Join
     */
    
    public Hall_Join() {
        initComponents();
    }

    public Hall_Join(String info[][], int itr) {
        initComponents();

        DefaultTableModel model = (DefaultTableModel) Hall_Join_Table.getModel();
        String data[] = new String[3];

        for (int i = 0; i < itr; i++) {

            for (int j = 0; j < 3; j++) {
                data[j] = info[i][j];
            }

            model.addRow(data);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton11 = new javax.swing.JButton();
        Showtime_Btn = new javax.swing.JButton();
        exStaff_Btn = new javax.swing.JButton();
        exShowtime_Btn = new javax.swing.JButton();
        Staff_Btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Hall_Join_Table = new javax.swing.JTable();

        jButton11.setText("Back");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Showtime_Btn.setText("SHOWTIME");
        Showtime_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Showtime_BtnActionPerformed(evt);
            }
        });

        exStaff_Btn.setText("Ex-STAFF");
        exStaff_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exStaff_BtnActionPerformed(evt);
            }
        });

        exShowtime_Btn.setText("Ex-SHOWTIME");
        exShowtime_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exShowtime_BtnActionPerformed(evt);
            }
        });

        Staff_Btn.setText("STAFF");
        Staff_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Staff_BtnActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("JOIN WITH");

        jButton12.setText("Back");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        Hall_Join_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "HallName", "HallType", "TotalSeat"
            }
        ));
        Hall_Join_Table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Hall_Join_Table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(Staff_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(exStaff_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(Showtime_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(exShowtime_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(397, 397, 397)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Staff_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exStaff_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Showtime_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exShowtime_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Staff_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Staff_BtnActionPerformed

        String query = "SELECT * from Hall INNER JOIN Staff ON Hall.HallName = Staff.HallName";

        int itr = 0;

        String[][] info = new String[1000][10];

        try {
            Connection con;
            PreparedStatement ps;
            ResultSet rs;
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=Register_Login;user=root;password=root");
            ps = con.prepareStatement(query);

            rs = ps.executeQuery();

            while (rs.next()) {

                String[] data = new String[10];

                info[itr][0] = rs.getString("HallName");
                info[itr][1] = rs.getString("HallType");
                info[itr][2] = rs.getString("TotalSeat");

                info[itr][3] = rs.getString("StaffID");
                info[itr][4] = rs.getString("FirstName");
                info[itr][5] = rs.getString("LastName");
                info[itr][6] = rs.getString("StartingTime");
                info[itr][7] = rs.getString("EndingTime");
                info[itr][8] = rs.getString("HallName");
                info[itr][9] = rs.getString("Salary");

                itr++;

//JOptionPane.showMessageDialog(null,"Yes");
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }

        new Hall_Join_Staff(info, itr).setVisible(true);
        setVisible(false);
        System.out.println(itr);

    }//GEN-LAST:event_Staff_BtnActionPerformed

    private void exStaff_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exStaff_BtnActionPerformed
        // TODO add your handling code here:

        String query = "SELECT * from Hall INNER JOIN ExStaff ON Hall.HallName = ExStaff.HallName";

        int itr = 0;

        String[][] info = new String[1000][10];

        try {
            Connection con;
            PreparedStatement ps;
            ResultSet rs;
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=Register_Login;user=root;password=root");
            ps = con.prepareStatement(query);

            rs = ps.executeQuery();

            while (rs.next()) {

                String[] data = new String[10];

                info[itr][0] = rs.getString("HallName");
                info[itr][1] = rs.getString("HallType");
                info[itr][2] = rs.getString("TotalSeat");

                info[itr][3] = rs.getString("StaffID");
                info[itr][4] = rs.getString("FirstName");
                info[itr][5] = rs.getString("LastName");
                info[itr][6] = rs.getString("StartingTime");
                info[itr][7] = rs.getString("EndingTime");
                info[itr][8] = rs.getString("HallName");
                info[itr][9] = rs.getString("Salary");

                itr++;

//JOptionPane.showMessageDialog(null,"Yes");
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }

        new Hall_Join_ExStaff(info, itr).setVisible(true);
        setVisible(false);
        System.out.println(itr);

    }//GEN-LAST:event_exStaff_BtnActionPerformed

    private void Showtime_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Showtime_BtnActionPerformed

        // TODO add your handling code here:
        String query = "SELECT * from Hall INNER JOIN Showtime ON Hall.HallName = Showtime.HallName";

        int itr = 0;

        String[][] info = new String[1000][10];

        try {
            Connection con;
            PreparedStatement ps;
            ResultSet rs;
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=Register_Login;user=root;password=root");
            ps = con.prepareStatement(query);

            rs = ps.executeQuery();

            while (rs.next()) {

                String[] data = new String[8];
                info[itr][0] = rs.getString("HallName");
                info[itr][1] = rs.getString("HallType");
                info[itr][2] = rs.getString("TotalSeat");

                info[itr][3] = rs.getString("Code");
                info[itr][4] = rs.getString("MovieName");
                info[itr][5] = rs.getString("StartingTime");
                info[itr][6] = rs.getString("EndingTime");
                info[itr][7] = rs.getString("TicketPrice");

                itr++;

//JOptionPane.showMessageDialog(null,"Yes");
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }

        new Hall_Join_Showtime(info, itr).setVisible(true);
        setVisible(false);
        System.out.println(itr);


    }//GEN-LAST:event_Showtime_BtnActionPerformed

    private void exShowtime_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exShowtime_BtnActionPerformed
        // TODO add your handling code here:

        String query = "SELECT * from Hall INNER JOIN Showtime ON Hall.HallName = Showtime.HallName";

        int itr = 0;

        String[][] info = new String[1000][10];

        try {
            Connection con;
            PreparedStatement ps;
            ResultSet rs;
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=Register_Login;user=root;password=root");
            ps = con.prepareStatement(query);

            rs = ps.executeQuery();

            while (rs.next()) {

                String[] data = new String[8];
                info[itr][0] = rs.getString("HallName");
                info[itr][1] = rs.getString("HallType");
                info[itr][2] = rs.getString("TotalSeat");

                info[itr][3] = rs.getString("Code");
                info[itr][4] = rs.getString("MovieName");
                info[itr][5] = rs.getString("StartingTime");
                info[itr][6] = rs.getString("EndingTime");
                info[itr][7] = rs.getString("TicketPrice");

                itr++;

//JOptionPane.showMessageDialog(null,"Yes");
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }

        new Hall_Join_ExShowtime(info, itr).setVisible(true);
        setVisible(false);
        System.out.println(itr);


    }//GEN-LAST:event_exShowtime_BtnActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        new AdminPanel().setVisible(true);
        setVisible(false);

        
        
     
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hall_Join.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hall_Join.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hall_Join.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hall_Join.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hall_Join().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Hall_Join_Table;
    private javax.swing.JButton Showtime_Btn;
    private javax.swing.JButton Staff_Btn;
    private javax.swing.JButton exShowtime_Btn;
    private javax.swing.JButton exStaff_Btn;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
