
import java.awt.List;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Pabon
 */
public class SearchDropDown extends javax.swing.JFrame {

    String[] codeList = new String[20];
    int codeSize = 0;
    private JSpinner spinner;

    /**
     * Creates new form SearchDropDown
     */
    public SearchDropDown() {
        initComponents();
        SpinnerHour.setVisible(false);
        TimeScrollPane.setVisible(false);
        TimeSearchButton.setVisible(false);
        DateChooser.setVisible(false);
        SpinnerMinute.setVisible(false);
        BuyTicketButton.setVisible(false);
        MovieFormatComboBox.setVisible(false);
        MovieFormatScrollPane.setVisible(false);
        GenreScrollPane.setVisible(false);
        Search_txt.setVisible(false);
        Search.setVisible(false);
        jScrollPane2.setVisible(false);
        GenreComboBox.setVisible(false);
        menu.add(jPanel1);

    }

    /**
     *
     * @param products
     * @param searchWord
     * @return
     */
    private void FillListBox() {

        DefaultListModel m = new DefaultListModel();

        try {

            Connection con;
            PreparedStatement ps;

            ResultSet rs;
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=Register_Login;user=root;password=root");
            String val = Search_txt.getText().trim();
            System.out.println(val);
            String query;

            query = "SELECT * from Showtime where MovieName like '%" + val + "%'";

            ps = con.prepareStatement(query);
            // ps.setString(1, Search_txt.getText());

            System.out.println(query);
            //ps.setString(1,val);
            rs = ps.executeQuery();

            while (rs.next()) {
                String movieName = rs.getString("MovieName");
                //System.out.println(movieName);
                m.addElement(movieName);

//JOptionPane.showMessageDialog(null,"Yes");
            }
            jList1.setModel(m);

        } catch (Exception ex) {

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        menu = new javax.swing.JPopupMenu();
        buttonGroup = new javax.swing.ButtonGroup();
        SearchByPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bg = new javax.swing.JPanel();
        Search_txt = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        Search = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        MovieNameTable = new javax.swing.JTable();
        GenreComboBox = new javax.swing.JComboBox<>();
        GenreScrollPane = new javax.swing.JScrollPane();
        GenreTable = new javax.swing.JTable();
        MovieFormatScrollPane = new javax.swing.JScrollPane();
        MovieFormatTable = new javax.swing.JTable();
        MovieFormatComboBox = new javax.swing.JComboBox<>();
        BuyTicketButton = new javax.swing.JButton();
        SpinnerMinute = new javax.swing.JSpinner();
        DateChooser = new com.toedter.calendar.JDateChooser();
        TimeSearchButton = new javax.swing.JButton();
        TimeScrollPane = new javax.swing.JScrollPane();
        TimeTable = new javax.swing.JTable();
        SpinnerHour = new javax.swing.JSpinner();

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jList1.setBackground(new java.awt.Color(51, 51, 51));
        jList1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jList1.setForeground(new java.awt.Color(255, 255, 255));
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jList1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jList1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 260));

        menu.setFocusable(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(854, 528));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SearchByPanel.setBackground(new java.awt.Color(0, 0, 0));
        SearchByPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Search By");
        SearchByPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 247, 39));

        getContentPane().add(SearchByPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 70));

        bg.setBackground(new java.awt.Color(51, 51, 51));
        bg.setForeground(new java.awt.Color(102, 102, 102));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Search_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Search_txtMouseClicked(evt);
            }
        });
        Search_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_txtActionPerformed(evt);
            }
        });
        Search_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Search_txtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Search_txtKeyTyped(evt);
            }
        });
        bg.add(Search_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 580, 30));

        buttonGroup.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Movie Name");
        jRadioButton1.setContentAreaFilled(false);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        bg.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 112, 30));

        buttonGroup.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Date & Time");
        jRadioButton2.setContentAreaFilled(false);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        bg.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 112, 30));

        buttonGroup.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("Genre");
        jRadioButton3.setContentAreaFilled(false);
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        bg.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 76, 30));

        buttonGroup.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("Movie Format");
        jRadioButton4.setContentAreaFilled(false);
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        bg.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, -1, 30));

        Search.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Search.setForeground(new java.awt.Color(255, 153, 0));
        Search.setText("Search");
        bg.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 50, 30));

        jScrollPane2.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));

        MovieNameTable.setBackground(new java.awt.Color(51, 51, 51));
        MovieNameTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MovieNameTable.setForeground(new java.awt.Color(255, 255, 255));
        MovieNameTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Movie Name", "Hall Name", "Date", "Starting Time", "Ending Time", "Type", "Genre", "Ticket Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        MovieNameTable.setFocusable(false);
        MovieNameTable.setSelectionBackground(new java.awt.Color(255, 153, 0));
        MovieNameTable.getTableHeader().setReorderingAllowed(false);
        MovieNameTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MovieNameTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(MovieNameTable);
        if (MovieNameTable.getColumnModel().getColumnCount() > 0) {
            MovieNameTable.getColumnModel().getColumn(0).setResizable(false);
            MovieNameTable.getColumnModel().getColumn(1).setResizable(false);
            MovieNameTable.getColumnModel().getColumn(2).setResizable(false);
            MovieNameTable.getColumnModel().getColumn(3).setResizable(false);
            MovieNameTable.getColumnModel().getColumn(4).setResizable(false);
            MovieNameTable.getColumnModel().getColumn(5).setResizable(false);
            MovieNameTable.getColumnModel().getColumn(6).setResizable(false);
            MovieNameTable.getColumnModel().getColumn(7).setResizable(false);
        }

        bg.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 820, 170));

        GenreComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Action", "Adventure", "Animation", "Comedy", "Crime", "Fantasy", "Historical", "Horror", "Romance", "Science Fiction", "Thriller" }));
        GenreComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenreComboBoxActionPerformed(evt);
            }
        });
        bg.add(GenreComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 580, 30));

        GenreTable.setBackground(new java.awt.Color(51, 51, 51));
        GenreTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GenreTable.setForeground(new java.awt.Color(255, 255, 255));
        GenreTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Genre", "Movie Name", "Hall Name", "Date", "Starting Time", "Ending Time", "Type", "Ticket Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        GenreTable.setRowSelectionAllowed(false);
        GenreTable.getTableHeader().setReorderingAllowed(false);
        GenreScrollPane.setViewportView(GenreTable);
        if (GenreTable.getColumnModel().getColumnCount() > 0) {
            GenreTable.getColumnModel().getColumn(0).setResizable(false);
            GenreTable.getColumnModel().getColumn(1).setResizable(false);
            GenreTable.getColumnModel().getColumn(2).setResizable(false);
            GenreTable.getColumnModel().getColumn(3).setResizable(false);
            GenreTable.getColumnModel().getColumn(4).setResizable(false);
            GenreTable.getColumnModel().getColumn(5).setResizable(false);
            GenreTable.getColumnModel().getColumn(6).setResizable(false);
            GenreTable.getColumnModel().getColumn(7).setResizable(false);
        }

        bg.add(GenreScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 860, 170));

        MovieFormatScrollPane.setBackground(new java.awt.Color(51, 51, 51));
        MovieFormatScrollPane.setForeground(new java.awt.Color(255, 255, 255));

        MovieFormatTable.setBackground(new java.awt.Color(51, 51, 51));
        MovieFormatTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MovieFormatTable.setForeground(new java.awt.Color(255, 255, 255));
        MovieFormatTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Movie Format", "Movie Name", "Hall Name", "Date", "Starting Time", "Ending Time", "Genre", "Ticket Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        MovieFormatTable.setRowSelectionAllowed(false);
        MovieFormatTable.setSelectionBackground(new java.awt.Color(255, 153, 0));
        MovieFormatTable.getTableHeader().setReorderingAllowed(false);
        MovieFormatScrollPane.setViewportView(MovieFormatTable);
        if (MovieFormatTable.getColumnModel().getColumnCount() > 0) {
            MovieFormatTable.getColumnModel().getColumn(0).setResizable(false);
            MovieFormatTable.getColumnModel().getColumn(1).setResizable(false);
            MovieFormatTable.getColumnModel().getColumn(2).setResizable(false);
            MovieFormatTable.getColumnModel().getColumn(3).setResizable(false);
            MovieFormatTable.getColumnModel().getColumn(4).setResizable(false);
            MovieFormatTable.getColumnModel().getColumn(5).setResizable(false);
            MovieFormatTable.getColumnModel().getColumn(6).setResizable(false);
            MovieFormatTable.getColumnModel().getColumn(7).setResizable(false);
        }

        bg.add(MovieFormatScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 820, 170));

        MovieFormatComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3D", "Regular" }));
        MovieFormatComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovieFormatComboBoxActionPerformed(evt);
            }
        });
        bg.add(MovieFormatComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 580, 30));

        BuyTicketButton.setBackground(new java.awt.Color(255, 255, 255));
        BuyTicketButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BuyTicketButton.setForeground(new java.awt.Color(255, 153, 0));
        BuyTicketButton.setText("Buy Ticket");
        BuyTicketButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        BuyTicketButton.setContentAreaFilled(false);
        BuyTicketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyTicketButtonActionPerformed(evt);
            }
        });
        bg.add(BuyTicketButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, 150, 30));

        SpinnerMinute.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        SpinnerMinute.setModel(new javax.swing.SpinnerNumberModel(0, 0, 24, 1));
        bg.add(SpinnerMinute, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 70, 60));

        DateChooser.setDateFormatString("yyyy/MM/dd");
        bg.add(DateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 190, 100));

        TimeSearchButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TimeSearchButton.setForeground(new java.awt.Color(255, 153, 0));
        TimeSearchButton.setText("Search");
        TimeSearchButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        TimeSearchButton.setContentAreaFilled(false);
        TimeSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimeSearchButtonActionPerformed(evt);
            }
        });
        bg.add(TimeSearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, 70, 30));

        TimeScrollPane.setBackground(new java.awt.Color(0, 0, 0));
        TimeScrollPane.setForeground(new java.awt.Color(255, 255, 255));

        TimeTable.setBackground(new java.awt.Color(51, 51, 51));
        TimeTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TimeTable.setForeground(new java.awt.Color(255, 255, 255));
        TimeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Starting Time", "Ending Time", "Date", "Movie Name", "Hall Name", "Type", "Genre", "Ticket Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TimeTable.setFocusable(false);
        TimeTable.setSelectionBackground(new java.awt.Color(255, 153, 0));
        TimeTable.getTableHeader().setReorderingAllowed(false);
        TimeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TimeTableMouseClicked(evt);
            }
        });
        TimeScrollPane.setViewportView(TimeTable);
        if (TimeTable.getColumnModel().getColumnCount() > 0) {
            TimeTable.getColumnModel().getColumn(0).setResizable(false);
            TimeTable.getColumnModel().getColumn(1).setResizable(false);
            TimeTable.getColumnModel().getColumn(2).setResizable(false);
            TimeTable.getColumnModel().getColumn(3).setResizable(false);
            TimeTable.getColumnModel().getColumn(4).setResizable(false);
            TimeTable.getColumnModel().getColumn(5).setResizable(false);
            TimeTable.getColumnModel().getColumn(6).setResizable(false);
            TimeTable.getColumnModel().getColumn(7).setResizable(false);
        }

        bg.add(TimeScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 820, 170));

        SpinnerHour.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bg.add(SpinnerHour, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 70, 60));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 910, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        SpinnerHour.setVisible(true);
        DateChooser.setVisible(true);
        TimeSearchButton.setVisible(true);
        SpinnerMinute.setVisible(true);
        GenreComboBox.setVisible(false);
        MovieFormatComboBox.setVisible(false);
        MovieFormatScrollPane.setVisible(false);
        GenreScrollPane.setVisible(false);
        Search_txt.setVisible(false);
        Search.setVisible(false);
        jScrollPane2.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void Search_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_txtActionPerformed
        DefaultListModel m = new DefaultListModel();

        try {

            Connection con;
            PreparedStatement ps;

            ResultSet rs;
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=Register_Login;user=root;password=root");
            String val = Search_txt.getText().trim();
            System.out.println(val);
            String query;

            query = "SELECT * from Showtime";

            ps = con.prepareStatement(query);
            // ps.setString(1, Search_txt.getText());

            System.out.println(query);
            //ps.setString(1,val);
            rs = ps.executeQuery();

            while (rs.next()) {
                String movieName = rs.getString("MovieName");
                //System.out.println(movieName);
                m.addElement(movieName);

//JOptionPane.showMessageDialog(null,"Yes");
            }
            jList1.setModel(m);

        } catch (Exception ex) {

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_Search_txtActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        SpinnerHour.setVisible(false);
        TimeScrollPane.setVisible(false);
        TimeSearchButton.setVisible(false);
        DateChooser.setVisible(false);
        SpinnerMinute.setVisible(false);
        Search_txt.setVisible(false);
        Search.setVisible(false);
        jScrollPane2.setVisible(false);
        GenreComboBox.setVisible(false);
        GenreScrollPane.setVisible(false);
        MovieFormatComboBox.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void Search_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Search_txtKeyReleased

        jPanel1.setVisible(true);
        menu.setVisible(true);
        String search = Search_txt.getText().trim();
        if (!search.equals("")) {
            System.out.println(search);
            menu.show(Search_txt, 0, Search_txt.getHeight());
        }// TODO add your handling code here:
        FillListBox();
    }//GEN-LAST:event_Search_txtKeyReleased

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        SpinnerHour.setVisible(false);
        SpinnerHour.setVisible(false);
        TimeScrollPane.setVisible(false);
        TimeSearchButton.setVisible(false);
        DateChooser.setVisible(false);
        SpinnerMinute.setVisible(false);
        GenreComboBox.setVisible(false);
        MovieFormatComboBox.setVisible(false);
        MovieFormatScrollPane.setVisible(false);
        GenreScrollPane.setVisible(false);
        Search_txt.setVisible(true);
        Search.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void Search_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Search_txtMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_Search_txtMouseClicked

    private void Search_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Search_txtKeyTyped
        //jScrollPane2.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_Search_txtKeyTyped

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        TimeScrollPane.setVisible(false);
        TimeSearchButton.setVisible(false);
        DateChooser.setVisible(false);
        SpinnerMinute.setVisible(false);
        SpinnerHour.setVisible(false);
        MovieFormatScrollPane.setVisible(false);
        MovieFormatComboBox.setVisible(false);
        Search_txt.setVisible(false);
        Search.setVisible(false);
        jScrollPane2.setVisible(false);
        GenreComboBox.setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void GenreComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenreComboBoxActionPerformed

        GenreScrollPane.setVisible(true);
        String tmp1 = GenreComboBox.getSelectedItem().toString();
        DefaultTableModel model = (DefaultTableModel) GenreTable.getModel();
        model.setRowCount(0);
        jPanel1.setVisible(false);
        menu.setVisible(false);

        int itr = 0;
        String[][] info = new String[1000][10];

        String query = "SELECT * from Showtime where Genre = ?";

        try {
            Connection con;
            PreparedStatement ps;
            ResultSet rs;
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=Register_Login;user=root;password=root");
            ps = con.prepareStatement(query);
            ps.setString(1, tmp1);
            rs = ps.executeQuery();

            while (rs.next()) {

                String[] data = new String[9];

                info[itr][0] = rs.getString("Genre");
                info[itr][1] = rs.getString("MovieName");
                info[itr][2] = rs.getString("HallName");
                info[itr][3] = rs.getString("ShowDate");
                info[itr][4] = rs.getString("StartingTime");
                info[itr][5] = rs.getString("EndingTime");
                info[itr][6] = rs.getString("ShowType");
                info[itr][7] = rs.getString("TicketPrice");

                itr++;
            }

            String data[] = new String[9];

            for (int i = 0; i < itr; i++) {

                for (int j = 0; j < 9; j++) {
                    data[j] = info[i][j];
                }

                model.addRow(data);
            }

        } catch (Exception ex) {
        }// TODO add your handling code here:
    }//GEN-LAST:event_GenreComboBoxActionPerformed

    private void MovieFormatComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovieFormatComboBoxActionPerformed
        MovieFormatScrollPane.setVisible(true);
        String tmp2 = MovieFormatComboBox.getSelectedItem().toString();
        DefaultTableModel model = (DefaultTableModel) MovieFormatTable.getModel();
        model.setRowCount(0);
        jPanel1.setVisible(false);
        menu.setVisible(false);

        int itr = 0;
        String[][] info = new String[1000][10];

        String query = "SELECT * from Showtime where ShowType = ?";

        try {
            Connection con;
            PreparedStatement ps;
            ResultSet rs;
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=Register_Login;user=root;password=root");
            ps = con.prepareStatement(query);
            ps.setString(1, tmp2);
            rs = ps.executeQuery();

            while (rs.next()) {

                String[] data = new String[9];

                info[itr][0] = rs.getString("ShowType");
                info[itr][1] = rs.getString("MovieName");
                info[itr][2] = rs.getString("HallName");
                info[itr][3] = rs.getString("ShowDate");
                info[itr][4] = rs.getString("StartingTime");
                info[itr][5] = rs.getString("EndingTime");
                info[itr][6] = rs.getString("Genre");
                info[itr][7] = rs.getString("TicketPrice");

                itr++;
            }

            String data[] = new String[9];

            for (int i = 0; i < itr; i++) {

                for (int j = 0; j < 9; j++) {
                    data[j] = info[i][j];
                }

                model.addRow(data);
            }

        } catch (Exception ex) {
        }// TODO add your handling code here:
    }//GEN-LAST:event_MovieFormatComboBoxActionPerformed

    private void jList1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList1KeyPressed

        //jScrollPane2.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jList1KeyPressed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked

        BuyTicketButton.setVisible(true);
        DefaultTableModel model = (DefaultTableModel) MovieNameTable.getModel();
        model.setRowCount(0);
        jPanel1.setVisible(false);
        menu.setVisible(false);
        jScrollPane2.setVisible(true);
        String tmp = (String) jList1.getSelectedValue();

        int itr = 0;
        String[][] info = new String[1000][10];

        String query = "SELECT * from Showtime where MovieName = ?";

        try {
            Connection con;
            PreparedStatement ps;
            ResultSet rs;
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=Register_Login;user=root;password=root");
            ps = con.prepareStatement(query);
            ps.setString(1, tmp);
            rs = ps.executeQuery();
            codeSize = 9;
            while (rs.next()) {

                String[] data = new String[9];

                info[itr][0] = rs.getString("MovieName");
                info[itr][1] = rs.getString("HallName");
                info[itr][2] = rs.getString("ShowDate");
                info[itr][3] = rs.getString("StartingTime");
                info[itr][4] = rs.getString("EndingTime");
                info[itr][5] = rs.getString("ShowType");
                info[itr][6] = rs.getString("Genre");
                info[itr][7] = rs.getString("TicketPrice");
                codeList[itr] = (rs.getString("Code"));
                System.out.println(codeList[itr]);
                itr++;
            }

            String data[] = new String[9];

            for (int i = 0; i < itr; i++) {

                for (int j = 0; j < 9; j++) {
                    data[j] = info[i][j];
                }

                model.addRow(data);
            }

            //new BuyNow(data, 4,2).setVisible(true);
        } catch (Exception ex) {
        }

        //System.out.println(itr);
        // TODO add your handling code here:
    }//GEN-LAST:event_jList1MouseClicked

    private void MovieNameTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MovieNameTableMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_MovieNameTableMouseClicked

    private void BuyTicketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuyTicketButtonActionPerformed

        System.out.println("codeSize = " + codeSize);
        int i = MovieNameTable.getSelectedRow();
        System.out.println(codeList[i]);
        int itr = 0;
        int[][] info = new int[1000][20];
        for (int l = 0; l < 10; l++) {
            System.out.println(codeList[l]);
        }
        String query = "SELECT * from Seat where Code = " + codeList[i];

        try {
            Connection con;
            PreparedStatement ps;
            ResultSet rs;
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=Register_Login;user=root;password=root");
            ps = con.prepareStatement(query);
            //ps.setString(1,(codeList[i]));
            rs = ps.executeQuery();
            int vacant = 0;
            if (rs.next()) {

                // String[] data = new String[9];
                info[1][1] = Integer.parseInt(rs.getString("R11"));
                info[1][2] = Integer.parseInt(rs.getString("R12"));
                info[1][3] = Integer.parseInt(rs.getString("R13"));
                info[2][1] = Integer.parseInt(rs.getString("R21"));
                info[2][2] = Integer.parseInt(rs.getString("R22"));
                info[2][3] = Integer.parseInt(rs.getString("R23"));
                info[3][1] = Integer.parseInt(rs.getString("R31"));
                info[3][2] = Integer.parseInt(rs.getString("R32"));
                info[3][3] = Integer.parseInt(rs.getString("R33"));
                info[4][1] = Integer.parseInt(rs.getString("R41"));
                info[4][2] = Integer.parseInt(rs.getString("R42"));
                info[4][3] = Integer.parseInt(rs.getString("R43"));
                vacant = Integer.parseInt(rs.getString("vacant"));

            }
            System.out.println("Vacant = " + Integer.toString(vacant));
            if (vacant != 0) {
                new BuyNow(info, 4, Integer.parseInt(codeList[i])).setVisible(true);
                //new BuyNow().setVisible(true); 
                setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "No Seats available");
            }

        } catch (Exception ex) {
        }// TODO add your handling code here:
    }//GEN-LAST:event_BuyTicketButtonActionPerformed

    private void TimeSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimeSearchButtonActionPerformed

        String valueM = SpinnerMinute.getValue().toString();
        String valueH = SpinnerHour.getValue().toString();
        //String date = DateChooser.getDate().toString();
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String date = df.format(DateChooser.getDate());

        DefaultTableModel model = (DefaultTableModel) TimeTable.getModel();
        model.setRowCount(0);
        jPanel1.setVisible(false);
        menu.setVisible(false);
        TimeScrollPane.setVisible(true);

        int itr = 0;
        String[][] info = new String[1000][10];

        String query = "SELECT * from Showtime where StartingTime >= '" + valueH + ":" + valueM + ":00' and ShowDate = '" + date + "'";
        System.out.println(query);
        try {
            Connection con;
            PreparedStatement ps;
            ResultSet rs;
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=Register_Login;user=root;password=root");
            ps = con.prepareStatement(query);
            rs = ps.executeQuery();

            while (rs.next()) {

                info[itr][0] = rs.getString("StartingTime");
                info[itr][1] = rs.getString("EndingTime");
                info[itr][2] = rs.getString("MovieName");
                info[itr][3] = rs.getString("ShowDate");
                info[itr][4] = rs.getString("HallName");
                info[itr][5] = rs.getString("ShowType");
                info[itr][6] = rs.getString("Genre");
                info[itr][7] = rs.getString("TicketPrice");
                itr++;
            }
            System.out.println(itr);
            String data[] = new String[9];

            for (int i = 0; i < itr; i++) {

                for (int j = 0; j < 9; j++) {
                    data[j] = info[i][j];
                }

                model.addRow(data);
            }

            //new BuyNow(data, 4,2).setVisible(true);
        } catch (Exception ex) {
        }

// TODO add your handling code here:
    }//GEN-LAST:event_TimeSearchButtonActionPerformed

    private void TimeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TimeTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TimeTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchDropDown.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchDropDown.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchDropDown.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchDropDown.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchDropDown().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuyTicketButton;
    private com.toedter.calendar.JDateChooser DateChooser;
    private javax.swing.JComboBox<String> GenreComboBox;
    private javax.swing.JScrollPane GenreScrollPane;
    private javax.swing.JTable GenreTable;
    private javax.swing.JComboBox<String> MovieFormatComboBox;
    private javax.swing.JScrollPane MovieFormatScrollPane;
    private javax.swing.JTable MovieFormatTable;
    private javax.swing.JTable MovieNameTable;
    private javax.swing.JLabel Search;
    private javax.swing.JPanel SearchByPanel;
    private javax.swing.JTextField Search_txt;
    private javax.swing.JSpinner SpinnerHour;
    private javax.swing.JSpinner SpinnerMinute;
    private javax.swing.JScrollPane TimeScrollPane;
    private javax.swing.JButton TimeSearchButton;
    private javax.swing.JTable TimeTable;
    private javax.swing.JPanel bg;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu menu;
    // End of variables declaration//GEN-END:variables
}
