
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rifat Waheed
 */
public class Trading_Activities extends javax.swing.JFrame {

    /**
     * Creates new form Trading_Activities
     */
    public Trading_Activities() {
        initComponents();
    }

    
           public Trading_Activities(String info[][], int itr) {
        initComponents();

        DefaultTableModel model = (DefaultTableModel) Tradings_Table_Display.getModel();
        String data[] = new String[6];

        for (int i = 0; i < itr; i++) {

            for (int j = 0; j < 6; j++) {
                data[j] = info[i][j];
            }

            model.addRow(data);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Insert_Date_txt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Total_Tradings_Btn = new javax.swing.JButton();
        Average_Tradings_Btn = new javax.swing.JButton();
        Minimum_Tradings_Btn = new javax.swing.JButton();
        Maximum_Tradings_Btn = new javax.swing.JButton();
        Result_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tradings_Table_Display = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Insert_Date_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Insert_Date_txtActionPerformed(evt);
            }
        });
        getContentPane().add(Insert_Date_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 281, 217, 36));

        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("       Result:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 67, 31));

        Total_Tradings_Btn.setBackground(new java.awt.Color(0, 0, 0));
        Total_Tradings_Btn.setForeground(new java.awt.Color(255, 153, 0));
        Total_Tradings_Btn.setText("Total Tradings");
        Total_Tradings_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Total_Tradings_BtnActionPerformed(evt);
            }
        });
        getContentPane().add(Total_Tradings_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 473, 158, 42));

        Average_Tradings_Btn.setBackground(new java.awt.Color(0, 0, 0));
        Average_Tradings_Btn.setForeground(new java.awt.Color(255, 153, 0));
        Average_Tradings_Btn.setText("Average");
        Average_Tradings_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Average_Tradings_BtnActionPerformed(evt);
            }
        });
        getContentPane().add(Average_Tradings_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(898, 473, 174, 42));

        Minimum_Tradings_Btn.setBackground(new java.awt.Color(0, 0, 0));
        Minimum_Tradings_Btn.setForeground(new java.awt.Color(255, 153, 0));
        Minimum_Tradings_Btn.setText("Minimum");
        Minimum_Tradings_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Minimum_Tradings_BtnActionPerformed(evt);
            }
        });
        getContentPane().add(Minimum_Tradings_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 473, 172, 42));

        Maximum_Tradings_Btn.setBackground(new java.awt.Color(0, 0, 0));
        Maximum_Tradings_Btn.setForeground(new java.awt.Color(255, 153, 0));
        Maximum_Tradings_Btn.setText("Maximum");
        Maximum_Tradings_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Maximum_Tradings_BtnActionPerformed(evt);
            }
        });
        getContentPane().add(Maximum_Tradings_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 473, 153, 42));
        getContentPane().add(Result_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 357, 217, 36));

        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Insert Date :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 284, 67, 31));

        Tradings_Table_Display.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cost", "Customer Name", "Phone", "Code", "Date"
            }
        ));
        jScrollPane1.setViewportView(Tradings_Table_Display);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 11, 907, 228));

        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("YY/MM/DD");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(786, 275, 217, 48));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 153, 0));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 533, 91, 37));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1250, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Total_Tradings_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Total_Tradings_BtnActionPerformed
        // TODO add your handling code here:
        
                 
        String query = "SELECT Count (ID)as ss from Tradings where Date=?";
      
            int itr = 0;
            
            String [][]info = new String [1000][10]; 
            
         try {
            Connection con;
            PreparedStatement ps;
            ResultSet rs;
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=Register_Login;user=root;password=root");
            ps = con.prepareStatement(query);

            ps.setString(1, Insert_Date_txt.getText());

            rs = ps.executeQuery();

            String tt = "";

            while (rs.next()) {
                tt = (rs.getString("ss"));
                Result_txt.setText(tt);
                itr++;
            }

        } catch (Exception ex) {
        }
      

     
    }//GEN-LAST:event_Total_Tradings_BtnActionPerformed

    private void Insert_Date_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Insert_Date_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Insert_Date_txtActionPerformed

    private void Average_Tradings_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Average_Tradings_BtnActionPerformed
        // TODO add your handling code here:
        
        
        
                                 
        String query = "SELECT Avg (Cost)as ss from Tradings where Date=?";
      
            int itr = 0;
            
            String [][]info = new String [1000][10]; 
            
          try {
            Connection con;
         PreparedStatement ps;
         ResultSet rs;
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        
           con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=Register_Login;user=root;password=root");
           ps = con.prepareStatement(query);
           
           ps.setString(1,Insert_Date_txt.getText());
           
           
                   
            rs = ps.executeQuery();  
            
            String tt="" ;
            
            while ( rs.next()){
                tt= (rs.getString("ss"));
                Result_txt.setText(tt);
                itr++;
            }
         
    

      
        
        } catch (Exception ex) {
        }
      

        
    }//GEN-LAST:event_Average_Tradings_BtnActionPerformed

    private void Minimum_Tradings_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Minimum_Tradings_BtnActionPerformed
        // TODO add your handling code here:
        
        
 
                         
        String query = "SELECT Min (Cost)as ss from Tradings where Date=?";
      
            int itr = 0;
            
            String [][]info = new String [1000][10]; 
            
          try {
            Connection con;
         PreparedStatement ps;
         ResultSet rs;
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        
           con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=Register_Login;user=root;password=root");
           ps = con.prepareStatement(query);
           
           ps.setString(1,Insert_Date_txt.getText());
           
           
                   
            rs = ps.executeQuery();  
            
            String tt="" ;
            
            while ( rs.next()){
                tt= (rs.getString("ss"));
                Result_txt.setText(tt);
                itr++;
            }
   
     
        } catch (Exception ex) {
        }
 
    }//GEN-LAST:event_Minimum_Tradings_BtnActionPerformed

    private void Maximum_Tradings_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Maximum_Tradings_BtnActionPerformed
        // TODO add your handling code here:
        
                                 
        String query = "SELECT Max (Cost)as ss from Tradings where Date=?";
      
            int itr = 0;
            
            String [][]info = new String [1000][10]; 
            
          try {
            Connection con;
         PreparedStatement ps;
         ResultSet rs;
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        
           con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=Register_Login;user=root;password=root");
           ps = con.prepareStatement(query);
           
           ps.setString(1,Insert_Date_txt.getText());
           
           
                   
            rs = ps.executeQuery();  
            
            String tt="" ;
            
            while ( rs.next()){
                tt= (rs.getString("ss"));
                Result_txt.setText(tt);
                itr++;
            }
         
  
        
          } catch (Exception ex) {
        }
        
        
        
    }//GEN-LAST:event_Maximum_Tradings_BtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        new AdvancedAdminPanel().setVisible(true);
        
        setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trading_Activities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trading_Activities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trading_Activities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trading_Activities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trading_Activities().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Average_Tradings_Btn;
    private javax.swing.JTextField Insert_Date_txt;
    private javax.swing.JButton Maximum_Tradings_Btn;
    private javax.swing.JButton Minimum_Tradings_Btn;
    private javax.swing.JTextField Result_txt;
    private javax.swing.JButton Total_Tradings_Btn;
    private javax.swing.JTable Tradings_Table_Display;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
